adminEventLoggingConfiguration:
  credentials: test
  secondaryCredentials: test
  projectId: test
  logName: test

stripe:
  apiKey: secret://stripe_key
  idempotencyKeyGenerator: secret://stripe_key_gen
  boostDescription: test
  supportedCurrencies:
    - usd

braintree:
  merchantId: smc9twpq2c3ns2qq
  publicKey: q562w5sdm2kxwcj5
  privateKey: secret://braintree_private_key
  environment: sandbox
  supportedCurrencies:
    - usd
  graphqlUrl: test
  merchantAccounts:
    a: test
    b: test
  circuitBreaker:
    failureRateThreshold: 50

dynamoDbClientConfiguration: 
  region: af-south-1
  clientExecutionTimeout: 30000
  clientRequestTimeout: 10000

awsAttachments:
  accessKey: secret://aws_access_key
  accessSecret: secret://aws_access_secret
  bucket: test
  region: af-south-1

cdn:
  accessKey: secret://aws_access_key
  accessSecret: secret://aws_access_secret
  bucket: test
  region: af-south-1

gcpAttachments:
  domain: test
  email: test
  maxSizeInBytes: 8000000
  pathPrefix: /test
  rsaSigningKey: secret://gcp_rsa_key

datadog:
  apiKey: secret://datadog_api_key
  step: 1000000
  environment: prod
  batchSize: 50000000

#Redis
cacheCluster:
  configurationUri: redis://127.0.0.1:6379
  timeout: 30000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 1000000

pubsub:
  uri: redis://127.0.0.1:6379
  timeout: 100000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception

metricsCluster:
  configurationUri: redis://127.0.0.1:6379
  timeout: 300000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

pushSchedulerCluster:
  configurationUri: redis://127.0.0.1:6379
  timeout: 300000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

rateLimitersCluster:
  configurationUri: redis://127.0.0.1:6379
  timeout: 300000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

clientPresenceCluster:
  configurationUri: redis://127.0.0.1:6379
  timeout: 300000
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

messageCache:
  persistDelayMinutes: 10
  cluster:
    configurationUri: redis://127.0.0.1:6379
    timeout: 300000
    circuitBreaker:
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowSize: 100
      slidingWindowMinimumNumberOfCalls: 100
      waitDurationInOpenStateInSeconds: 10
      ignoredExceptions:
        - java.lang.Exception
    retry:
      maxAttempts: 3
      waitDuration: 100000

directoryV2:
  clientConfiguration:
    userAuthenticationTokenSharedSecret: secret://token
    userIdTokenSharedSecret: secret://token

svr2:
  uri: test
  userAuthenticationTokenSharedSecret: secret://token
  userIdTokenSharedSecret: secret://token
  svrCaCertificates:
   - test1
   - test2
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

accountDatabaseCrawler:
  chunkSize: 1000

testDevices:
  - android
  - grapheneOS

maxDevices:
  - 
    number: test
    count: 1

limits:
  backupAuthCheck: 
    bucketSize: 10
    permitRegenerationDuration: 10000

webSocket:
  maxBinaryMessageSize: 2621440
  maxTextMessageSize: 2621440

fcm: 
  credentials: secret://test

apn:
  teamId: test
  keyId: test
  signingKey: secret://test
  bundleId: test
  sandbox: false

unidentifiedDelivery:
  certificate: secret://test
  privateKey: secret://token
  expiresDays: 2

challenge:
  blindingSecret: secret://test
  tokenTtl: 50000

recaptcha: 
  projectPath: test
  credentialConfigurationJson: test
  secondaryCredentialConfigurationJson: test

hCaptcha:
  apiKey: secret://test

storageService:
  userAuthenticationTokenSharedSecret: secret://test
  uri: test
  storageCaCertificates:
    - test
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

backupService:
  userAuthenticationTokenSharedSecret: secret://test
  uri: test
  backupCaCertificates:
    - test
  circuitBreaker:
    failureRateThreshold: 50
    permittedNumberOfCallsInHalfOpenState: 10
    slidingWindowSize: 100
    slidingWindowMinimumNumberOfCalls: 100
    waitDurationInOpenStateInSeconds: 10
    ignoredExceptions:
      - java.lang.Exception
  retry:
    maxAttempts: 3
    waitDuration: 100000

paymentsService:
  userAuthenticationTokenSharedSecret: secret://test
  coinMarketCapApiKey: secret://test
  fixerApiKey: secret://test
  coinMarketCapCurrencyIds:
    a: 1
  paymentCurrencies:
    - USD

artService:
  userAuthenticationTokenSharedSecret: secret://test
  userAuthenticationTokenUserIdSecret: secret://test
  tokenExpiration: 1000000

zkConfig:
  serverSecret: secret://test
  serverPublic: test

genericZkConfig:
  serverSecret: secret://test

remoteConfig:
  authorizedUsers:
    - test
  requiredHostedDomain: test
  audiences:
    - test
  globalConfig:
    test: test

appConfig:
  environment: test
  application: test
  configuration: test

badges:
  badges:
  badgeIdsEnabledForAll:
  receiptLevels:

subscription:
  badgeGracePeriod: 1000000
  levels:
    1: 
      badge: test
      prices: 
        a: 
          amount: 10

oneTimeDonations:
  boost:
    badge: boost
    level: 1
    expiration: 10000
  gift:
    badge: gift
    level: 2
    expiration: 20000
  currencies:
    usd:
      minimum: 1
      gift: 1
      boosts: [1,2,3,4,5,6]


spamFilterConfiguration:
  environment: prod

registrationService:
  host: test
  port: 8963
  credentialConfigurationJson: test
  secondaryCredentialConfigurationJson: test
  identityTokenAudience: test
  registrationCaCertificate: test

turn:
  secret: secret://test

grpcPort: 9876

dynamoDbTables: 
  accounts:
    tableName: accounts
    phoneNumberTableName: phoneNumberTableName
    phoneNumberIdentifierTableName: phoneNumberIdentifierTableName
    usernamesTableName: usernamesTableName
    scanPageSize: 100
  deletedAccounts:
    tableName: deletedAccounts
  deletedAccountsLock:
    tableName: deletedAccountsLock
  ecKeys:
    tableName: ecKeys
  ecSignedPreKeys:
    tableName: ecSignedPreKeys
  kemKeys:
    tableName: kemKeys
  kemLastResortKeys:
    tableName: kemLastResortKeys
  pendingAccounts:
    tableName: pendingAccounts
  pendingDevices:
    tableName: pendingDevices
  phoneNumberIdentifiers:
    tableName: phoneNumberIdentifiers
  profiles:
    tableName: profiles
  pushChallenge:
    tableName: pushChallenge
  remoteConfig:
    tableName: remoteConfig
  reportMessage:
    tableName: reportMessage
  subscriptions:
    tableName: subscriptions
  verificationSessions:
    tableName: verificationSessions
  messages:
    tableName: messages
    expiration: 100000
  redeemedReceipts:
    tableName: redeemedReceipts
    expiration: 100000
  registrationRecovery:
    tableName: registrationRecovery
    expiration: 100000
  issuedReceipts:
    tableName: issuedReceipts
    expiration: 100000
    generator: test





