apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f pandora.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: signal
    database: postgres
  name: signal
  namespace: pandora
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: signal
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f pandora.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/swarm-default: "true"
        io.kompose.service: signal
    spec:
      volumes:
      - name: secret-signal
        secret:
          secretName: signal
      containers:
        - image: tempacrpandora.azurecr.io/tempacrpandora/signal:latest
          volumeMounts:
          - name: secret-signal
            readOnly: true
            mountPath: "/home/pandora/config"
          env:
            - name: PANDORA_ENV
              value: ./config/azure.yml
          name: signal
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Gi"
              cpu: "500000m"
      restartPolicy: Always
status: {}
