apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f pandora.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: wipe
  name: wipe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wipe
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f pandora.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/swarm-default: "true"
        io.kompose.service: wipe
    spec:
      containers:
        - image: khalifarsm/pandora-wipe
          name: wipe
          ports:
            - containerPort: 80
              hostPort: 8103
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
