apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f pandora.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresql
  name: postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f pandora.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/swarm-default: "true"
        io.kompose.service: postgresql
    spec:
      containers:
        - env:
            - name: PANDORA_ENV
              value: kube
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_MAX_CONNECTIONS
              value: "1000"
            - name: POSTGRES_PASSWORD
              value: "123456789"
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13-alpine
          name: postgresql
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-data29
      restartPolicy: Always
      volumes:
        - name: postgresql-claim0
          persistentVolumeClaim:
            claimName: postgresql-claim0
            readOnly: true
        - name: postgresql-data29
          persistentVolumeClaim:
            claimName: postgresql-data29
status: {}
